<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="YLMF-1711181457" name="com.mjitech.qa.test.AddSkuToCart" tests="6" failures="1" timestamp="11 六月 2019 06:32:58 GMT" time="24.173" errors="0">
  <testcase name="wxpay_callback_test" time="0.000" classname="com.mjitech.qa.test.AddSkuToCart">
    <skipped/>
  </testcase> <!-- wxpay_callback_test -->
  <testcase name="get_order_detail" time="0.000" classname="com.mjitech.qa.test.AddSkuToCart">
    <skipped/>
  </testcase> <!-- get_order_detail -->
  <testcase name="add_sku_to_cart" time="24.173" classname="com.mjitech.qa.test.AddSkuToCart">
    <failure type="junit.framework.ComparisonFailure" message="expected:&lt;[fals]e&gt; but was:&lt;[tru]e&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[fals]e> but was:<[tru]e>
at junit.framework.Assert.assertEquals(Assert.java:85)
at junit.framework.Assert.assertEquals(Assert.java:91)
at com.mjitech.qa.test.AddSkuToCart.add_sku_to_cart(AddSkuToCart.java:144)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- add_sku_to_cart -->
  <testcase name="submitCart" time="0.000" classname="com.mjitech.qa.test.AddSkuToCart">
    <skipped/>
  </testcase> <!-- submitCart -->
  <testcase name="getPayUrl" time="0.000" classname="com.mjitech.qa.test.AddSkuToCart">
    <skipped/>
  </testcase> <!-- getPayUrl -->
  <testcase name="get_order_detail_by_takingnumber" time="0.000" classname="com.mjitech.qa.test.AddSkuToCart">
    <skipped/>
  </testcase> <!-- get_order_detail_by_takingnumber -->
</testsuite> <!-- com.mjitech.qa.test.AddSkuToCart -->
